### ISSUE TITLE
function jsonValue escaping the wrong variable in default case

### ISSUE THREAD

**Issue by soapdog** [bhall2001/fastjson#13]
The private jsonValue() function is escaping a variable called `pText` in its default case when the variable should be `pValue`.  this leads to corrupt json full of newlines and other non-conformant stuff.

**Comment by bhall2001** [comment]
Verified this is a bug. Squashed.

**Comment by bhall2001** [comment]
Fixed in 4.0.1

**Comment by bhall2001** [comment]
This has been fixed. Closed based on my testing and lack of further reports the issue still exists. I do believe this bug also caused other reports of issues with fastJson but since this is corrected, I have not been able to replicate other reports and have closed them as well.
