### ISSUE TITLE
The private function isNumericArray does not work for very large datasets

### ISSUE THREAD

**Issue by soapdog** [bhall2001/fastjson#14]
The private function called isNumericArray is returning false for very large numeric arrays. The RegEx is failing to extract the keys. Tested with 500k worth of response in a single numeric array. Maybe its our LiveCode Server engine that can't use that RegEx expression.

Replacing that filter call with a slower loop will make this work and doesn't impact much on performance.

**Comment by bhall2001** [comment]
please send me a sample dataset  for testing.

thanks.

**Comment by bhall2001** [comment]
I did some work today in the isNumericalArray routine. I did take your advice and use a loop to detect numbers. Turns out the filter command does not use RegEx expressions but a syntax that looks like RegEx. My hope is the loop I have there now will work. Let me know.

Thanks for the input!!!!!
