### ISSUE TITLE
Library is not unescaping forward slashes

### ISSUE THREAD

**Issue by soapdog** [bhall2001/fastjson#15]
When decoding a json back into an array the library is missing all forward slashes. So your array values are filled with stuff such as `\/` instead of `/`

**Comment by bhall2001** [comment]
This may have been a side effect of the pText bug. Check it again and let me know if it's fixed with the code in the 4.0.1 branch.

**Comment by bhall2001** [comment]
I believe this was related to a another issue. I have not been able to replicate in latest version.
