### ISSUE TITLE
Problem in "isJson" function 

### ISSUE THREAD

**Issue by madpink** [bhall2001/fastjson#27]
on an iOS device, this complete locks up the program... here's what happens...

in this instance, the response from the site is NOT a JSON, but is instead a 404 error
the problem seems to come with line 227:
`put sJson[n-3] & return & sJson[n-2] &  return & sJson[n-1] &  return & sJson[n] &  return & sJson[n+1] &  return
`

in the Livecode IDE, this causes the message box to open up and display some characters, but in a compiled iOS app, everything freezes when it gets to this point 

removing this line fixed the problem for me, as the next step is simply to return false
not sure what that line was meant to do...

**Comment by bhall2001** [comment]
Fixed in version 1.1.1
