### ISSUE TITLE
JSON starting with [ does not work

### ISSUE THREAD

**Issue by bhall2001** [bhall2001/fastjson#9]
Any JSON string that starts with [ does not work in my tester script. Not sure if this is a problem with the sample stack or with the library. Getting this down so I remember to investigate it.

**Comment by madpink** [comment]
do you mean a JSON like this?

{"test":"[value]"}

**Comment by bhall2001** [comment]
no. [{color: "red", value: "#f00"}]

**Comment by madpink** [comment]
What about:
 [{color: "red", value: "#f00"},{color: "green", value: "#f02"}]

if it is within brackets, it should technically contain more than 1 object

**Comment by bhall2001** [comment]
I'm labeling this a bug. Found some issues with how fastJson handles arrays for data. I'm going to need some help on this I suspect. Not sure why this is so hard for me to get my head around...

**Comment by bhall2001** [comment]
This has been fixed. Closed based on my testing and lack of further reports the issue still exists.
